name: Docs

on:
  push:
    paths:
      - 'docs/**'

jobs:
  build:
    name: Build documentation site
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Generate XML documentation
        uses: cake-build/cake-action@v1
        with:
          target: Analyze
      - name: Run benchmarks
        uses: cake-build/cake-action@v1
        with:
          target: Benchmark
      - name: Install dependencies
        run: npm ci
        working-directory: docs
      - name: Build site
        run: npm run build
        working-directory: docs
      - name: Publish changes
        run: npm run publish
        working-directory: docs
